### ISSUE TITLE
Another "Debugger" package already exists within "atom-community"?

### ISSUE THREAD

**Issue by marlyn-x86** [atom-community/debug#2]
<a href=https://github.com/atom-community/debugger>It appears there's already a "debugger" package within the "atom-community"  @group</a> - to avoid fracturing work, should effort be focused there instead?

**Comment by bugaevc** [comment]
Also can we please get any update on what's going on?  Doesn't seem to be actively developed, at all.

**Comment by thomasjo** [comment]
The `debugger` and `debug` packages are not really overlapping in terms of functionality. This package is meant as a unified package that orchestrates other debuggers. Essentially it is meant to consume "debug" providers. For other such examples see e.g. [lint](https://github.com/atom-community/lint) and [run](https://github.com/atom-community/run).

For the time being, these packages are not being actively developed and they have been published in order to control the package names.

Hopefully @joefitzgerald, myself and other interested parties can discuss and flesh out some ideas in the coming months. We need to agree on a sense of direction before we begin tackling these projects.
